### ISSUE TITLE
Objective Section Review

### ISSUE THREAD

**Issue by jordanwillis** [blairhardaker/bwa-u4-feature-request#1]
First off, nice job on your feature request document!  I will go through each section and leave any feedback, recommendations, or comments in an Issue tied to each section.

To start things off, your short and sweet objective section is pretty good.  Obviously the main idea here is to convey the idea of the feature is one sentence or less so that readers can quickly understand the essence of the feature and what is to come in the remaining document.

My only recommendation would be to perhaps add just a bit more description so that it is clear what the feature actually is, and my second recommendation is to always write this section from the user's perspective.  This will hopefully baseline all readers to ensure they understand what it means for the user.  Perhaps something like this...

> Enable users to click on a song anywhere in the app and hear a 30 second music preview of the selected song.

Here I've added just a bit more detail so that the full scope of the feature can be understand from the objective section alone as well as provide some action to illustrate how the user would interact with the feature.

**Comment by blairhardaker** [comment]
Thankyou, will keep in mind that this should be written from the users perspective and contain a little more detail of the features usability.
