### ISSUE TITLE
Technical Design Section

### ISSUE THREAD

**Issue by jordanwillis** [blairhardaker/bwa-u4-feature-request#3]
Similarly, your technical design section is very good!  I felt like a software engineer with minimal experience with the application would be able to pick up this feature request and implement it without too much trouble since you decomposed the necessary work into smaller chunks.  I also liked that you included some mock ups for the relevant user interface portion of the implementation.

Over all, this is a very well put together technical specification for how to implement the preview feature.

**Comment by blairhardaker** [comment]
Thankyou.
