### ISSUE TITLE
Caveats Section

### ISSUE THREAD

**Issue by jordanwillis** [blairhardaker/bwa-u4-feature-request#4]
Lastly, your Caveats section is one of the more complete versions that I have seen thus far!  Not only did you mention the potential drawbacks of long preview times and all that entails, but provided some good alternatives that help meet the same objective of "allowing a user to confirm the selected song is what they wanted" beyond just by listening (e.g. via album art, etc.).

Overall you did a fantastic job on this project and I think you highlighted a very worthwhile feature for the Jammming app.  I would highly encourage you to complete the actual implementation if you have the time, to further practice your newly gained React skills.

Grade = Exceeds Expectations!!

Keep up the great work!

**Comment by blairhardaker** [comment]
Thankyou, appreciate your time in reviewing the project. I have learn a lot from both the project itself and the production of the feature request document. Will look to add the feature request when i get a spare few hours!
